version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    command: mongod --bind_ip_all

  app:
    build: .
    container_name: inventory-service
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017
      DATABASE_NAME: your_database_name
      SERVER_ADDRESS: :8080
    depends_on:
      - mongodb

volumes:
  mongo-data: