/*
 * Inventory Service API
 *
 * API documentation for the Inventory Service
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UpdateInventoryResponse struct {

	Success bool `json:"success,omitempty"`

	Message string `json:"message,omitempty"`
}
