/*
 * Inventory Service API
 *
 * API documentation for the Inventory Service
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UpdateInventoryRequest struct {

	Quantity int32 `json:"quantity,omitempty"`
}
