/*
 * Inventory Service API
 *
 * API documentation for the Inventory Service
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Product struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Quantity int32 `json:"quantity,omitempty"`

	Price float32 `json:"price,omitempty"`
}
